#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-copy"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "sublink-worker-SUBLINK_KV-COPY", id = "2c16b9434a55406cb974c36824d67a56" }
]

[assets]
directory = "./public"
